
from __future__ import annotations

from django.db import models


class DeviceModel(models.Model):
    """Managed network device."""

    STATUS_CHOICES = (
        ("online", "Online"),
        ("offline", "Offline"),
        ("unknown", "Unknown"),
    )

    hostname = models.CharField(max_length=120)
    management_ip = models.GenericIPAddressField(unique=True)
    vendor = models.CharField(max_length=80, default="Extreme Networks")
    model = models.CharField(max_length=80, default="AP130")
    firmware = models.CharField(max_length=120, blank=True, default="")
    serial = models.CharField(max_length=120, blank=True, default="")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="unknown")
    ssh_port = models.PositiveIntegerField(default=22)
    ssh_username = models.CharField(max_length=120, blank=True, default="")
    ssh_password = models.CharField(max_length=255, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["hostname"]
        verbose_name = "Device"
        verbose_name_plural = "Devices"

    def __str__(self) -> str:
        return f"{self.hostname} ({self.management_ip})"


class InterfaceModel(models.Model):
    """Current interface state for a device."""

    device = models.ForeignKey(
        DeviceModel,
        on_delete=models.CASCADE,
        related_name="interfaces",
    )
    name = models.CharField(max_length=80)
    status = models.CharField(max_length=20, default="unknown")
    speed = models.CharField(max_length=40, blank=True, default="")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        unique_together = ("device", "name")
        verbose_name = "Interface"
        verbose_name_plural = "Interfaces"

    def __str__(self) -> str:
        return f"{self.device.hostname} - {self.name}"


class ClientModel(models.Model):
    """Current connected client state for a device."""

    device = models.ForeignKey(
        DeviceModel,
        on_delete=models.CASCADE,
        related_name="clients",
    )
    mac = models.CharField(max_length=32)
    ip = models.GenericIPAddressField(blank=True, null=True)
    hostname = models.CharField(max_length=255, blank=True, default="")
    signal = models.IntegerField(default=0)
    rx = models.CharField(max_length=40, blank=True, default="")
    tx = models.CharField(max_length=40, blank=True, default="")
    is_online = models.BooleanField(default=True)
    last_seen = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["hostname", "mac"]
        unique_together = ("device", "mac")
        verbose_name = "Client"
        verbose_name_plural = "Clients"

    def __str__(self) -> str:
        return self.hostname or self.mac


class SnapshotModel(models.Model):
    """Historical device collection snapshot."""

    device = models.ForeignKey(
        DeviceModel,
        on_delete=models.CASCADE,
        related_name="snapshots",
    )
    timestamp = models.DateTimeField()
    duration = models.FloatField(default=0.0)
    payload = models.JSONField(default=dict)

    class Meta:
        ordering = ["-timestamp", "-id"]
        verbose_name = "Snapshot"
        verbose_name_plural = "Snapshots"

    def __str__(self) -> str:
        return f"{self.device.hostname} @ {self.timestamp.isoformat()}"


class ClientSnapshotModel(models.Model):
    """Historical client presence per snapshot."""

    snapshot = models.ForeignKey(
        SnapshotModel,
        on_delete=models.CASCADE,
        related_name="client_snapshots",
    )
    device = models.ForeignKey(
        DeviceModel,
        on_delete=models.CASCADE,
        related_name="client_history",
    )
    mac = models.CharField(max_length=32)
    ip = models.GenericIPAddressField(blank=True, null=True)
    hostname = models.CharField(max_length=255, blank=True, default="")
    signal = models.IntegerField(default=0)
    rx = models.CharField(max_length=40, blank=True, default="")
    tx = models.CharField(max_length=40, blank=True, default="")
    is_online = models.BooleanField(default=True)
    first_seen = models.DateTimeField(null=True, blank=True)
    last_seen = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["hostname", "mac"]
        verbose_name = "Client Snapshot"
        verbose_name_plural = "Client Snapshots"

    def __str__(self) -> str:
        return self.hostname or self.mac


class EventModel(models.Model):
    """Operational events generated by the platform."""

    SEVERITY_CHOICES = (
        ("info", "Info"),
        ("warning", "Warning"),
        ("error", "Error"),
    )

    device = models.ForeignKey(
        DeviceModel,
        on_delete=models.CASCADE,
        related_name="events",
    )
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, default="info")
    message = models.TextField()
    occurred_at = models.DateTimeField()

    class Meta:
        ordering = ["-occurred_at", "-id"]
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self) -> str:
        return f"{self.device.hostname} - {self.severity}"
