# Generated by Django 5.1.15 on 2026-07-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_clientsnapshotmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmodel",
            options={
                "ordering": ["hostname", "mac"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="devicemodel",
            options={
                "ordering": ["hostname"],
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="eventmodel",
            options={
                "ordering": ["-occurred_at", "-id"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="interfacemodel",
            options={
                "ordering": ["name"],
                "verbose_name": "Interface",
                "verbose_name_plural": "Interfaces",
            },
        ),
        migrations.AlterModelOptions(
            name="snapshotmodel",
            options={
                "ordering": ["-timestamp", "-id"],
                "verbose_name": "Snapshot",
                "verbose_name_plural": "Snapshots",
            },
        ),
        migrations.RemoveField(
            model_name="clientmodel",
            name="created_at",
        ),
        migrations.AddField(
            model_name="interfacemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="hostname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="mac",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="rx",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="tx",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="firmware",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="model",
            field=models.CharField(default="AP130", max_length=80),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="serial",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="ssh_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="ssh_username",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="vendor",
            field=models.CharField(default="Extreme Networks", max_length=80),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="severity",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interfacemodel",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="interfacemodel",
            name="speed",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="interfacemodel",
            name="status",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="snapshotmodel",
            name="duration",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="snapshotmodel",
            name="payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterModelTable(
            name="clientmodel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="devicemodel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="eventmodel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="interfacemodel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="snapshotmodel",
            table=None,
        ),
    ]
